"""init

Revision ID: b97d1f9402fa
Revises: 
Create Date: 2024-12-05 12:30:51.999392

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils




# revision identifiers, used by Alembic.
revision = 'b97d1f9402fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('subscriber', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', name=op.f('pk_users'))
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('address', 'user_id', name=op.f('uq_wallets_address'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_table('users')
    # ### end Alembic commands ###
