"""NAME

Revision ID: da12fda96414
Revises: b97d1f9402fa
Create Date: 2024-12-09 08:14:26.550766

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils




# revision identifiers, used by Alembic.
revision = 'da12fda96414'
down_revision = 'b97d1f9402fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
