"""settings

Revision ID: e2940a0f0f75
Revises: da12fda96414
Create Date: 2024-12-10 08:50:30.873020

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils




# revision identifiers, used by Alembic.
revision = 'e2940a0f0f75'
down_revision = 'da12fda96414'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_trade', sa.Integer(), nullable=True),
    sa.Column('max_trade', sa.Integer(), nullable=True),
    sa.Column('min_cap', sa.Float(), nullable=True),
    sa.Column('max_cap', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.add_column('users', sa.Column('settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_users_settings_id_settings'), 'users', 'settings', ['settings_id'], ['id'])
    op.add_column('wallets', sa.Column('settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_wallets_settings_id_settings'), 'wallets', 'settings', ['settings_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_wallets_settings_id_settings'), 'wallets', type_='foreignkey')
    op.drop_column('wallets', 'settings_id')
    op.drop_constraint(op.f('fk_users_settings_id_settings'), 'users', type_='foreignkey')
    op.drop_column('users', 'settings_id')
    op.drop_table('settings')
    # ### end Alembic commands ###
